apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-prediction-app
  labels:
    app: udacity-prediction-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-prediction-app
  template:
    metadata:
      labels:
        app: udacity-prediction-app
    spec:
      containers:
      - name: udacity-prediction-app
        image: mostafaabdelrahman/boston-housing-prediction:latest
        ports:
        - containerPort: 80